version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Main Tests
          command: npm test:live:e2e
      - run:
          name: Tag and Release New Version
          command: npx semantic-release
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Main Tests
          command: npm test:live:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

