version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Main Tests
          command: npm run test
      - run:
          name: Tag and Release New Version
          command: npx semantic-release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

